### ISSUE TITLE
Derby database location different from when using java org.apache.derby.tools.ij

### ISSUE THREAD

**Issue by v-machado** [nakagami/pydrda#3]
Hi, I was not being able to connect to a Database I've set and I realized it was happening because my Derby database default location was on "C:\Users\[my user]\", while pydrda was looking for it in the bin folder of my Derby installation folder (C:\Apache\Derby\bin). Do you know if it is a malfunction of the package or if it is some misconfiguration of mine?

**Comment by nakagami** [comment]
Umm, I don't know why

**Comment by nakagami** [comment]
derby.system.home ? https://db.apache.org/derby/docs/10.1/tuning/rtunproper32066.html

**Comment by v-machado** [comment]
It might be. For now I'll just use it in the place where it has set as default. Everything else is just fine so far. Thank you.
