### ISSUE TITLE
Error connecting to DB2 (ModuleNotFoundError: No module named 'pyDes')

### ISSUE THREAD

**Issue by snsina** [nakagami/pydrda#6]
Hi Hajime,

I hope you are doing well, thanks for your beautiful work. we use your library for a while to connect to db2 for development, unfortunately when we tried to connect to db2 with des encryption we get this error
I figured out pyDes library is not included I appreciate your help.

Here is sample of connection string
drda.connect(host=db2_host, database=db2_database, user=db_username, password=db_password, port=db2_port)

  File "/tmp/drda.zip/drda/__init__.py", line 122, in connect
    return Connection(host, database, port, user, password, use_ssl, db_type)
  File "/tmp/drda.zip/drda/connection.py", line 194, in __init__
    self.encoding
  File "/tmp/drda.zip/drda/ddm.py", line 290, in packSECCHK
    des = secmec9.des(sectkn, private_key)
  File "/tmp/drda.zip/drda/secmec9.py", line 51, in des
    import pyDes
ModuleNotFoundError: No module named 'pyDes'

Thanks,

**Comment by nakagami** [comment]
`pip install pydrda` should also install pyDes, but if not, try running `pip install pyDes`.

**Comment by snsina** [comment]
Thanks for quick response, unfortunately we cannot use pip install since we need to package drda and upload to aws to run as serverless tasks. we need to find a way to include pyDes into a package and call it.

I'd appreciate if you show us a way to package everything into same package.

Thanks

**Comment by nakagami** [comment]
Sorry
If you download and ungzip the file and put it in the PYTHONPATH location, you should be able to use it.

**Comment by snsina** [comment]
Thanks, it went through.

I had to create a zip file just having pyDes.py, initially I put pyDes.py in pyDes folder + __init__.py but for some reason pydrda could not import it

**Comment by nakagami** [comment]
Try copying pyDes.py into drda folder

**Comment by nakagami** [comment]
This is not a README compliant installation, so this issue is closed.
