### ISSUE TITLE
Release of the newest version

### ISSUE THREAD

**Issue by Walz** [nakagami/pydrda#8]
Hello,

@nakagami can you please bump `pydrdra` version and release the newest version on pypi ?

Thanks,
@Walz

**Comment by nakagami** [comment]
I'm up to date with what I'm uploading to pypi.
Is there anything wrong with it?

**Comment by Walz** [comment]
The latest version `0.4.3` does not contain the last commit which adds the timeout parameter.

**Comment by nakagami** [comment]
I'm sorry.
I merged the pull request, but didn't pull it locally, and forgot about it.

I don't plan to add any other features, so I'm releasing the current version as 0.4.4.

**Comment by nakagami** [comment]
done

**Comment by Walz** [comment]
Thank you !
